import type { CSSProperties } from "react";
import type { ResolvedTheme } from "@/types/appearance";

export function resolvedThemeToCssVars(resolved: ResolvedTheme): CSSProperties {
  const { colors, typography, design, branding } = resolved;
  const spacingScale = design.spacing.scale;

  return {
    "--color-primary": colors.primary,
    "--color-primary-dark": colors.primaryDark,
    "--color-secondary": colors.secondary,
    "--color-accent": colors.accent,
    "--color-background": colors.background,
    "--color-surface": colors.surface,
    "--color-card": colors.card,
    "--color-text": colors.text,
    "--color-muted": colors.muted,
    "--color-steel": colors.steel,
    "--color-graphite": colors.graphite,
    "--color-line": colors.line,
    "--color-border": colors.border,
    "--color-sidebar": colors.sidebar,
    "--color-header": colors.header,
    "--color-success": colors.success,
    "--color-warning": colors.warning,
    "--color-danger": colors.error,
    "--color-error": colors.error,
    "--color-info": colors.info,
    "--font-heading-name": typography.headingFont,
    "--font-body-name": typography.bodyFont,
    "--text-body": typography.baseFontSize,
    "--text-h1": typography.headingSizes.h1,
    "--text-h2": typography.headingSizes.h2,
    "--text-h3": typography.headingSizes.h3,
    "--text-h4": typography.headingSizes.h4,
    "--font-weight-heading": String(typography.fontWeights.heading),
    "--font-weight-body": String(typography.fontWeights.body),
    "--font-weight-bold": String(typography.fontWeights.bold),
    "--leading-heading": String(typography.lineHeights.heading),
    "--leading-body": String(typography.lineHeights.body),
    "--tracking-tight": typography.letterSpacing.tight,
    "--tracking-wide": typography.letterSpacing.wide,
    "--radius-sm": design.radius.sm,
    "--radius-md": design.radius.md,
    "--radius-lg": design.radius.lg,
    "--radius-xl": design.radius.xl,
    "--shadow-sm": design.shadows.sm,
    "--shadow-md": design.shadows.md,
    "--shadow-lg": design.shadows.lg,
    "--space-scale": String(spacingScale),
    "--admin-sidebar-width": design.layout.sidebarWidth,
    "--admin-header-height": design.layout.headerHeight,
    "--admin-content-max": design.layout.contentMaxWidth,
    "--admin-sidebar-bg": design.sidebar.background,
    "--admin-sidebar-text": design.sidebar.text,
    "--admin-sidebar-muted": design.sidebar.mutedText,
    "--admin-sidebar-active-bg": design.sidebar.activeBackground,
    "--admin-sidebar-active-text": design.sidebar.activeText,
    "--admin-sidebar-border": design.sidebar.borderColor,
    "--admin-header-bg": design.header.background,
    "--admin-header-text": design.header.text,
    "--admin-header-border": design.header.borderColor,
    "--admin-btn-radius": design.components.button.radius,
    "--admin-card-radius": design.components.card.radius,
    "--admin-card-shadow": design.components.card.shadow,
    "--admin-card-border": design.components.card.borderColor,
    "--admin-input-radius": design.components.input.radius,
    "--admin-input-border": design.components.input.borderColor,
    "--admin-input-focus": design.components.input.focusRing,
    "--admin-table-header-bg": design.components.table.headerBackground,
    "--admin-table-row-hover": design.components.table.rowHover,
    "--admin-table-border": design.components.table.borderColor,
    "--admin-badge-radius": design.components.badge.radius,
    "--admin-alert-radius": design.components.alert.radius,
    "--brand-logo": `url("${branding.logo}")`,
    "--brand-logo-light": `url("${branding.logoLight}")`,
    "--brand-logo-dark": `url("${branding.logoDark}")`,
    "--brand-mobile-logo": `url("${branding.mobileLogo}")`,
    "--brand-favicon": `url("${branding.favicon}")`,
    "--brand-application-name": `"${branding.applicationName.replace(/"/g, '\\"')}"`,
    "--brand-name": `"${branding.brandName.replace(/"/g, '\\"')}"`,
  } as CSSProperties;
}

export function resolvedThemeToLegacyTokens(resolved: ResolvedTheme) {
  return {
    colors: {
      primary: resolved.colors.primary,
      primaryDark: resolved.colors.primaryDark,
      secondary: resolved.colors.secondary,
      accent: resolved.colors.accent,
      background: resolved.colors.background,
      surface: resolved.colors.surface,
      text: resolved.colors.text,
      muted: resolved.colors.muted,
      steel: resolved.colors.steel,
      graphite: resolved.colors.graphite,
      line: resolved.colors.line,
    },
    fonts: {
      heading: resolved.typography.headingFont,
      body: resolved.typography.bodyFont,
    },
    radius: {
      sm: resolved.design.radius.sm,
      md: resolved.design.radius.md,
      lg: resolved.design.radius.lg,
    },
  };
}
